name: Build APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer Action
        uses: hmsjy2017/buildozer-action@v1
        with:
          # Solo compilar para 64 bits (más rápido y compatible)
          arch: arm64-v8a
          # Aceptar licencias automáticamente
          accept-sdk-license: true
