name: Build APK
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y autoconf automake libtool cmake libncurses5-dev libssl-dev openjdk-17-jdk wget unzip python3-pip

      - name: Instalar Buildozer
        run: pip install buildozer

      - name: Descargar NDK 25c
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O /tmp/ndk.zip
          unzip -q /tmp/ndk.zip -d $HOME/.buildozer/android/platform/

      - name: Configurar variable de entorno para el NDK
        run: echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25c" >> $GITHUB_ENV

      - name: Compilar APK
        run: buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
